/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicacoesRouteImport } from './routes/publicacoes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as CriativosRouteImport } from './routes/criativos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AvataresRouteImport } from './routes/avatares'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIdRouteImport } from './routes/produtos.$id'
import { Route as PerfisIdRouteImport } from './routes/perfis.$id'
import { Route as ConfiguracoesProvedoresRouteImport } from './routes/configuracoes.provedores'
import { Route as ConfiguracoesGeminiRouteImport } from './routes/configuracoes.gemini'
import { Route as AvataresIdRouteImport } from './routes/avatares.$id'

const PublicacoesRoute = PublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const CriativosRoute = CriativosRouteImport.update({
  id: '/criativos',
  path: '/criativos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvataresRoute = AvataresRouteImport.update({
  id: '/avatares',
  path: '/avatares',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIdRoute = ProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProdutosRoute,
} as any)
const PerfisIdRoute = PerfisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PerfisRoute,
} as any)
const ConfiguracoesProvedoresRoute = ConfiguracoesProvedoresRouteImport.update({
  id: '/provedores',
  path: '/provedores',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesGeminiRoute = ConfiguracoesGeminiRouteImport.update({
  id: '/gemini',
  path: '/gemini',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const AvataresIdRoute = AvataresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AvataresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/avatares': typeof AvataresRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/criativos': typeof CriativosRoute
  '/custos': typeof CustosRoute
  '/inteligencia': typeof InteligenciaRoute
  '/perfis': typeof PerfisRouteWithChildren
  '/produtos': typeof ProdutosRouteWithChildren
  '/publicacoes': typeof PublicacoesRoute
  '/avatares/$id': typeof AvataresIdRoute
  '/configuracoes/gemini': typeof ConfiguracoesGeminiRoute
  '/configuracoes/provedores': typeof ConfiguracoesProvedoresRoute
  '/perfis/$id': typeof PerfisIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/avatares': typeof AvataresRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/criativos': typeof CriativosRoute
  '/custos': typeof CustosRoute
  '/inteligencia': typeof InteligenciaRoute
  '/perfis': typeof PerfisRouteWithChildren
  '/produtos': typeof ProdutosRouteWithChildren
  '/publicacoes': typeof PublicacoesRoute
  '/avatares/$id': typeof AvataresIdRoute
  '/configuracoes/gemini': typeof ConfiguracoesGeminiRoute
  '/configuracoes/provedores': typeof ConfiguracoesProvedoresRoute
  '/perfis/$id': typeof PerfisIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/avatares': typeof AvataresRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/criativos': typeof CriativosRoute
  '/custos': typeof CustosRoute
  '/inteligencia': typeof InteligenciaRoute
  '/perfis': typeof PerfisRouteWithChildren
  '/produtos': typeof ProdutosRouteWithChildren
  '/publicacoes': typeof PublicacoesRoute
  '/avatares/$id': typeof AvataresIdRoute
  '/configuracoes/gemini': typeof ConfiguracoesGeminiRoute
  '/configuracoes/provedores': typeof ConfiguracoesProvedoresRoute
  '/perfis/$id': typeof PerfisIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automacoes'
    | '/avatares'
    | '/configuracoes'
    | '/criativos'
    | '/custos'
    | '/inteligencia'
    | '/perfis'
    | '/produtos'
    | '/publicacoes'
    | '/avatares/$id'
    | '/configuracoes/gemini'
    | '/configuracoes/provedores'
    | '/perfis/$id'
    | '/produtos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automacoes'
    | '/avatares'
    | '/configuracoes'
    | '/criativos'
    | '/custos'
    | '/inteligencia'
    | '/perfis'
    | '/produtos'
    | '/publicacoes'
    | '/avatares/$id'
    | '/configuracoes/gemini'
    | '/configuracoes/provedores'
    | '/perfis/$id'
    | '/produtos/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/automacoes'
    | '/avatares'
    | '/configuracoes'
    | '/criativos'
    | '/custos'
    | '/inteligencia'
    | '/perfis'
    | '/produtos'
    | '/publicacoes'
    | '/avatares/$id'
    | '/configuracoes/gemini'
    | '/configuracoes/provedores'
    | '/perfis/$id'
    | '/produtos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AutomacoesRoute: typeof AutomacoesRoute
  AvataresRoute: typeof AvataresRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  CriativosRoute: typeof CriativosRoute
  CustosRoute: typeof CustosRoute
  InteligenciaRoute: typeof InteligenciaRoute
  PerfisRoute: typeof PerfisRouteWithChildren
  ProdutosRoute: typeof ProdutosRouteWithChildren
  PublicacoesRoute: typeof PublicacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publicacoes': {
      id: '/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criativos': {
      id: '/criativos'
      path: '/criativos'
      fullPath: '/criativos'
      preLoaderRoute: typeof CriativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatares': {
      id: '/avatares'
      path: '/avatares'
      fullPath: '/avatares'
      preLoaderRoute: typeof AvataresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$id': {
      id: '/produtos/$id'
      path: '/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof ProdutosIdRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/perfis/$id': {
      id: '/perfis/$id'
      path: '/$id'
      fullPath: '/perfis/$id'
      preLoaderRoute: typeof PerfisIdRouteImport
      parentRoute: typeof PerfisRoute
    }
    '/configuracoes/provedores': {
      id: '/configuracoes/provedores'
      path: '/provedores'
      fullPath: '/configuracoes/provedores'
      preLoaderRoute: typeof ConfiguracoesProvedoresRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/gemini': {
      id: '/configuracoes/gemini'
      path: '/gemini'
      fullPath: '/configuracoes/gemini'
      preLoaderRoute: typeof ConfiguracoesGeminiRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/avatares/$id': {
      id: '/avatares/$id'
      path: '/$id'
      fullPath: '/avatares/$id'
      preLoaderRoute: typeof AvataresIdRouteImport
      parentRoute: typeof AvataresRoute
    }
  }
}

interface AvataresRouteChildren {
  AvataresIdRoute: typeof AvataresIdRoute
}

const AvataresRouteChildren: AvataresRouteChildren = {
  AvataresIdRoute: AvataresIdRoute,
}

const AvataresRouteWithChildren = AvataresRoute._addFileChildren(
  AvataresRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesGeminiRoute: typeof ConfiguracoesGeminiRoute
  ConfiguracoesProvedoresRoute: typeof ConfiguracoesProvedoresRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesGeminiRoute: ConfiguracoesGeminiRoute,
  ConfiguracoesProvedoresRoute: ConfiguracoesProvedoresRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface PerfisRouteChildren {
  PerfisIdRoute: typeof PerfisIdRoute
}

const PerfisRouteChildren: PerfisRouteChildren = {
  PerfisIdRoute: PerfisIdRoute,
}

const PerfisRouteWithChildren =
  PerfisRoute._addFileChildren(PerfisRouteChildren)

interface ProdutosRouteChildren {
  ProdutosIdRoute: typeof ProdutosIdRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosIdRoute: ProdutosIdRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AutomacoesRoute: AutomacoesRoute,
  AvataresRoute: AvataresRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  CriativosRoute: CriativosRoute,
  CustosRoute: CustosRoute,
  InteligenciaRoute: InteligenciaRoute,
  PerfisRoute: PerfisRouteWithChildren,
  ProdutosRoute: ProdutosRouteWithChildren,
  PublicacoesRoute: PublicacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
